from moviepy.editor import VideoFileClip, AudioFileClip, ImageClip, CompositeVideoClip
import json
import os

# 1. Load the script data generated by n8n
with open('allLines.json', 'r') as f:
    data = json.load(f)

# 2. Load the Minecraft background (Make sure it's at least 90s long)
bg = VideoFileClip("background.mp4")

clips = [bg]
current_time = 0

# 3. Loop through every line to overlay the "stickers"
for i, line in enumerate(data['script']):
    audio_path = f"audio_{i}.mp3"
    img_path = f"image_{i}.png"
    
    if os.path.exists(audio_path) and os.path.exists(img_path):
        audio = AudioFileClip(audio_path)
        duration = audio.duration
        
        # Create the character overlay
        # .mask_color(color=[0, 255, 0]) removes the #00FF00 green background
        sticker = (ImageClip(img_path)
                   .set_duration(duration)
                   .set_start(current_time)
                   .set_audio(audio)
                   .resize(height=500) # Makes them nice and big
                   .margin(bottom=50, right=50, opacity=0)
                   .set_position(("center", "bottom"))) # Centers them at the bottom
        
        clips.append(sticker)
        current_time += duration

# 4. Final Export
final_video = CompositeVideoClip(clips).set_duration(current_time)
final_video.write_videofile("final_podcast.mp4", fps=24, codec="libx264")
print("--- Video Generated Successfully: final_podcast.mp4 ---")
